import 'server-only'
import { and, asc, eq, sql } from 'drizzle-orm'
import { db } from '@/db'
import { coupons, customers, rewards } from '@/db/schema'
import { getPointsBalance, recordPoints, type LoyaltyConfig } from './loyalty'
import { tierAllows } from './rewards-meta'

/**
 * متجر المكافآت.
 *
 * النقاط من غير حاجة تتصرف فيها مجرد رقم بيكبر. المتجر ده هو اللي
 * بيدّي النقاط معنى: العميل بيبدّلها بخصم حقيقي، والتاجر بيتحكّم في
 * سعر كل مكافأة بالنقاط.
 *
 * الاسترداد بيولّد **كوبون باسم العميل**: كده الخصم بيمشي في نفس مسار
 * الكوبونات المتحقَّق منه على الخادم، بدل ما نخترع طريق خصم تاني لازم
 * يتأمّن من الأول.
 */

export type RewardRow = typeof rewards.$inferSelect

// الثوابت في rewards-meta عشان المتصفح يقدر يستوردها
export { REWARD_TYPES, TIER_LABELS, TIER_ORDER, rewardTypeLabel, tierAllows } from './rewards-meta'
export type { Tier } from './rewards-meta'

/** المكافآت المعروضة للعميل — النشطة اللي لسه فيها كمية */
export async function listActiveRewards(storeId: string): Promise<RewardRow[]> {
  return db
    .select()
    .from(rewards)
    .where(
      and(
        eq(rewards.storeId, storeId),
        eq(rewards.isActive, true),
        sql`(${rewards.stock} is null or ${rewards.stock} > 0)`,
      ),
    )
    .orderBy(asc(rewards.sortOrder), asc(rewards.pointsCost))
}

export type RedeemResult = { ok: true; code: string; label: string } | { ok: false; message: string }

/**
 * استرداد مكافأة بالنقاط.
 *
 * كل الفحوصات بتتم هنا على الخادم من قاعدة البيانات: الرصيد والمستوى
 * والكمية. الواجهة بتخفي المكافأة اللي مش مؤهّل ليها، لكن الإخفاء
 * تحسين شكلي — لو اعتمدنا عليه، أي طلب مباشر بيسترد أي حاجة.
 *
 * الخصم والكوبون في معاملة واحدة: لو الكوبون فشل، النقاط ما تنخصمش.
 * العميل يفقد نقاطه من غير ما ياخد حاجة أسوأ من إنه ما استردّش أصلًا.
 */
export async function redeemReward(input: {
  storeId: string
  customerId: string
  rewardId: string
  settings: LoyaltyConfig | null
}): Promise<RedeemResult> {
  if (!input.settings?.enabled) return { ok: false, message: 'نظام النقاط مقفول' }

  const [reward] = await db
    .select()
    .from(rewards)
    .where(and(eq(rewards.id, input.rewardId), eq(rewards.storeId, input.storeId)))
    .limit(1)

  if (!reward || !reward.isActive) return { ok: false, message: 'المكافأة دي مش متاحة' }
  if (reward.stock !== null && reward.stock <= 0) return { ok: false, message: 'المكافأة دي خلصت' }

  const [customer] = await db
    .select({ id: customers.id, tier: customers.tier })
    .from(customers)
    .where(and(eq(customers.id, input.customerId), eq(customers.storeId, input.storeId)))
    .limit(1)

  if (!customer) return { ok: false, message: 'الحساب مش موجود' }
  if (!tierAllows(customer.tier, reward.minTier)) {
    return { ok: false, message: 'المكافأة دي لمستوى أعلى' }
  }

  const balance = await getPointsBalance(input.customerId)
  if (balance < reward.pointsCost) {
    return { ok: false, message: `محتاج ${reward.pointsCost - balance} نقطة كمان` }
  }

  const code = rewardCode()
  const expires = new Date()
  expires.setDate(expires.getDate() + 90)

  try {
    await db.transaction(async (tx) => {
      await tx.insert(coupons).values({
        storeId: input.storeId,
        code,
        description: `مكافأة ولاء: ${reward.name}`,
        type:
          reward.type === 'coupon_percent'
            ? 'percent'
            : reward.type === 'coupon_fixed'
              ? 'fixed'
              : 'free_shipping',
        value: reward.type === 'free_shipping' || reward.type === 'free_product' ? 0 : reward.value,
        // الكود باسم العميل — التحقق بيرفضه من أي حد تاني
        eligibility: 'specific_customers',
        eligibilityValue: [input.customerId],
        usageLimit: 1,
        usageLimitPerCustomer: 1,
        isAutoGenerated: true,
        endsAt: expires,
      })

      if (reward.stock !== null) {
        await tx
          .update(rewards)
          .set({ stock: sql`greatest(0, ${rewards.stock} - 1)` })
          .where(eq(rewards.id, reward.id))
      }

      await tx
        .update(rewards)
        .set({ redeemedCount: sql`${rewards.redeemedCount} + 1` })
        .where(eq(rewards.id, reward.id))
    })
  } catch {
    return { ok: false, message: 'حصلت مشكلة في الاسترداد — جرّب تاني' }
  }

  await recordPoints({
    storeId: input.storeId,
    customerId: input.customerId,
    points: -reward.pointsCost,
    type: 'redeem',
    reason: `استرداد: ${reward.name}`,
  })

  return { ok: true, code, label: reward.name }
}

/**
 * كود المكافأة.
 *
 * من غير الحروف اللي بتتلخبط لما العميل يقراها من الشاشة ويكتبها:
 * صفر وO، وواحد وI وL. الكود بيتقرا ويتكتب باليد فعلًا.
 */
function rewardCode(): string {
  const alphabet = '23456789ABCDEFGHJKMNPQRSTUVWXYZ'
  let out = 'RW'
  for (let i = 0; i < 6; i++) {
    out += alphabet[Math.floor(Math.random() * alphabet.length)]
  }
  return out
}
