import 'server-only'
import { and, eq, sql } from 'drizzle-orm'
import { db } from '@/db'
import { coupons, wheelPrizes, wheelSettings, wheelSpins } from '@/db/schema'
import { generateToken } from './crypto'
import { normalizePhone } from './utils'

/**
 * عجلة الحظ.
 *
 * القاعدة الحاكمة: **السحب بيتم على الخادم بالكامل.** المتصفح بيعرض
 * دوران العجلة بس — النتيجة بتيجي جاهزة منّنا. لو خلّينا المتصفح
 * يسحب، أي حد يفتح الأدوات ويدّي نفسه الجايزة الكبيرة.
 *
 * والاحتمالات بنقاط الأساس (مجموعها ١٠٠٠٠) عشان التاجر يظبّط نسبة
 * كل جايزة بدقة من غير كسور عشرية.
 */

export type WheelPrize = typeof wheelPrizes.$inferSelect

export type SpinResult =
  | { ok: true; prize: { id: string; label: string; type: string; couponCode?: string }; index: number }
  | { ok: false; error: string }

export async function getWheelConfig(storeId: string) {
  const [settings] = await db
    .select()
    .from(wheelSettings)
    .where(eq(wheelSettings.storeId, storeId))
    .limit(1)

  if (!settings?.enabled) return null

  const prizes = await db
    .select()
    .from(wheelPrizes)
    .where(and(eq(wheelPrizes.storeId, storeId), eq(wheelPrizes.isActive, true)))
    .orderBy(wheelPrizes.position)

  if (prizes.length < 2) return null
  return { settings, prizes }
}

/**
 * سحب جايزة.
 *
 * بنستخدم عجلة روليت مرجّحة: بنجمع الاحتمالات ونختار رقمًا عشوائيًا
 * داخل المجموع. الجوائز اللي خلصت حصّتها اليومية بتتشال قبل السحب،
 * فاحتمالاتها بتتوزّع على الباقي تلقائيًا.
 */
export async function spinWheel(input: {
  storeId: string
  storeName: string
  phone: string
  email?: string | null
}): Promise<SpinResult> {
  const config = await getWheelConfig(input.storeId)
  if (!config) return { ok: false, error: 'العجلة مش متاحة دلوقتي' }

  const phone = normalizePhone(input.phone)
  if (phone.replace(/\D/g, '').length < 10) {
    return { ok: false, error: 'اكتب رقم تليفون صحيح' }
  }

  // حد اللفّات اليومية لكل رقم
  const [todaySpins] = await db
    .select({ n: sql<number>`count(*)::int` })
    .from(wheelSpins)
    .where(
      and(
        eq(wheelSpins.storeId, input.storeId),
        eq(wheelSpins.phone, phone),
        sql`${wheelSpins.createdAt} > now() - interval '1 day'`,
      ),
    )

  if ((todaySpins?.n ?? 0) >= config.settings.freeSpinsPerDay) {
    return { ok: false, error: 'خلصت لفّاتك النهاردة. جرّب بكرة.' }
  }

  // نشيل الجوائز اللي خلصت حصّتها اليومية
  const available = config.prizes.filter(
    (p) => p.dailyLimit === null || p.wonCount < p.dailyLimit,
  )
  if (available.length === 0) return { ok: false, error: 'الجوائز خلصت النهاردة' }

  const total = available.reduce((n, p) => n + p.probabilityBps, 0)
  if (total <= 0) return { ok: false, error: 'إعدادات الجوائز غير صحيحة' }

  let roll = Math.floor(Math.random() * total)
  let won = available[available.length - 1]
  for (const p of available) {
    roll -= p.probabilityBps
    if (roll < 0) {
      won = p
      break
    }
  }

  // كوبون الجايزة — كود لمرة واحدة صالح ٧ أيام
  let couponCode: string | undefined
  if (won.type === 'coupon_percent' || won.type === 'coupon_fixed' || won.type === 'free_shipping') {
    couponCode = `WIN${generateToken(4).toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 6)}`
    await db.insert(coupons).values({
      storeId: input.storeId,
      code: couponCode,
      description: `جايزة عجلة الحظ: ${won.label}`,
      type:
        won.type === 'coupon_percent' ? 'percent' : won.type === 'coupon_fixed' ? 'fixed' : 'free_shipping',
      value: won.value,
      usageLimit: 1,
      usageLimitPerCustomer: 1,
      isAutoGenerated: true,
      endsAt: new Date(Date.now() + 7 * 86_400_000),
      isActive: true,
    })
  }

  await db.transaction(async (tx) => {
    /**
     * بنسجّل اسم الجايزة مع معرّفها: لو التاجر عدّل الجوائز أو حذفها
     * بعدين، السجل يفضل مفهومًا ونعرف العميل كسب إيه.
     */
    await tx.insert(wheelSpins).values({
      storeId: input.storeId,
      prizeId: won.id,
      prizeLabel: won.label,
      phone,
      couponCode: couponCode ?? null,
    })

    await tx
      .update(wheelPrizes)
      .set({ wonCount: sql`${wheelPrizes.wonCount} + 1` })
      .where(eq(wheelPrizes.id, won.id))
  })

  return {
    ok: true,
    prize: { id: won.id, label: won.label, type: won.type, couponCode },
    index: config.prizes.findIndex((p) => p.id === won.id),
  }
}
