import { pgTable, uuid, text, boolean, integer, jsonb, timestamp, index, uniqueIndex } from 'drizzle-orm/pg-core'
import { stores } from './tenancy'
import { createdAt, updatedAt, money } from './_shared'

export type CouponType = 'percent' | 'fixed' | 'free_shipping'
export type CouponAppliesTo = 'all' | 'products' | 'categories'
export type CouponEligibility = 'all' | 'first_order' | 'tier' | 'specific_customers'

export const coupons = pgTable(
  'coupons',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    storeId: uuid('store_id').notNull().references(() => stores.id, { onDelete: 'cascade' }),
    code: text('code').notNull(),
    description: text('description'),

    type: text('type').$type<CouponType>().notNull().default('percent'),
    /** نسبة مئوية بنقاط الأساس (1000 = 10%) أو مبلغ ثابت بالوحدة الصغرى */
    value: integer('value').notNull().default(0),
    maxDiscount: money('max_discount'), // سقف الخصم لكوبونات النسبة
    minOrder: money('min_order'),

    appliesTo: text('applies_to').$type<CouponAppliesTo>().notNull().default('all'),
    targetIds: jsonb('target_ids').$type<string[]>().notNull().default([]),

    eligibility: text('eligibility').$type<CouponEligibility>().notNull().default('all'),
    eligibilityValue: jsonb('eligibility_value').$type<string[]>().notNull().default([]),

    usageLimit: integer('usage_limit'),
    usageLimitPerCustomer: integer('usage_limit_per_customer').notNull().default(1),
    usedCount: integer('used_count').notNull().default(0),

    /** كوبون هدية يُولَّد تلقائيًا (استرداد سلة، صفحة شكر، مكافأة ولاء) */
    isAutoGenerated: boolean('is_auto_generated').notNull().default(false),

    startsAt: timestamp('starts_at', { withTimezone: true }),
    endsAt: timestamp('ends_at', { withTimezone: true }),
    isActive: boolean('is_active').notNull().default(true),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex('coupons_store_code_unique').on(t.storeId, t.code),
    index('coupons_store_active_idx').on(t.storeId, t.isActive),
  ],
)

export const couponUses = pgTable(
  'coupon_uses',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    couponId: uuid('coupon_id').notNull().references(() => coupons.id, { onDelete: 'cascade' }),
    storeId: uuid('store_id').notNull().references(() => stores.id, { onDelete: 'cascade' }),
    orderId: uuid('order_id').notNull(),
    customerId: uuid('customer_id'),
    amount: money('amount'),
    createdAt: createdAt(),
  },
  (t) => [
    index('coupon_uses_coupon_idx').on(t.couponId),
    index('coupon_uses_customer_idx').on(t.customerId),
  ],
)

export type OfferType = 'quantity_break' | 'fixed_bundle' | 'mix_bundle' | 'buy_x_get_y'

/** عروض الكمية والباقات */
export const offers = pgTable(
  'offers',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    storeId: uuid('store_id').notNull().references(() => stores.id, { onDelete: 'cascade' }),
    type: text('type').$type<OfferType>().notNull(),
    name: text('name').notNull(),
    description: text('description'),
    /**
     * quantity_break: { tiers: [{ qty, discountBps }] }
     * fixed_bundle:   { productIds: [], bundlePrice }
     * mix_bundle:     { categoryIds: [], pickCount, bundlePrice }
     * buy_x_get_y:    { buyProductIds, buyQty, getProductIds, getQty, discountBps }
     */
    config: jsonb('config').$type<Record<string, unknown>>().notNull().default({}),
    productIds: jsonb('product_ids').$type<string[]>().notNull().default([]),
    badge: text('badge'),
    startsAt: timestamp('starts_at', { withTimezone: true }),
    endsAt: timestamp('ends_at', { withTimezone: true }),
    isActive: boolean('is_active').notNull().default(true),
    sortOrder: integer('sort_order').notNull().default(0),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('offers_store_active_idx').on(t.storeId, t.isActive)],
)

/** المسوّقون بالعمولة */
export const affiliates = pgTable(
  'affiliates',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    storeId: uuid('store_id').notNull().references(() => stores.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    phone: text('phone'),
    email: text('email'),
    code: text('code').notNull(),
    commissionType: text('commission_type').$type<'percent' | 'fixed'>().notNull().default('percent'),
    commissionValue: integer('commission_value').notNull().default(1000), // 10%
    balance: money('balance'),
    totalEarned: money('total_earned'),
    totalPaid: money('total_paid'),
    clicks: integer('clicks').notNull().default(0),
    conversions: integer('conversions').notNull().default(0),
    isActive: boolean('is_active').notNull().default(true),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex('affiliates_store_code_unique').on(t.storeId, t.code),
    index('affiliates_store_idx').on(t.storeId),
  ],
)

export const affiliateConversions = pgTable(
  'affiliate_conversions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    affiliateId: uuid('affiliate_id').notNull().references(() => affiliates.id, { onDelete: 'cascade' }),
    storeId: uuid('store_id').notNull().references(() => stores.id, { onDelete: 'cascade' }),
    orderId: uuid('order_id').notNull(),
    orderTotal: money('order_total'),
    commission: money('commission'),
    status: text('status').$type<'pending' | 'approved' | 'paid' | 'cancelled'>().notNull().default('pending'),
    createdAt: createdAt(),
  },
  (t) => [index('affiliate_conversions_affiliate_idx').on(t.affiliateId)],
)

/** الإحالات بين العملاء — «ادعُ صديقًا» */
export const referrals = pgTable(
  'referrals',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    storeId: uuid('store_id').notNull().references(() => stores.id, { onDelete: 'cascade' }),
    referrerCustomerId: uuid('referrer_customer_id').notNull(),
    referredCustomerId: uuid('referred_customer_id'),
    code: text('code').notNull(),
    orderId: uuid('order_id'),
    rewardPoints: integer('reward_points').notNull().default(0),
    status: text('status').$type<'pending' | 'completed' | 'rewarded'>().notNull().default('pending'),
    createdAt: createdAt(),
  },
  (t) => [
    /*
      صف لكل تحويل لا لكل كود: الكود ثابت على العميل (customers.
      referral_code) وبيتكرّر هنا مع كل صاحب بيستخدمه. الفهرس على
      العميل المُحال يمنع احتسابه مرتين لو استخدم كودين.
    */
    uniqueIndex('referrals_store_referred_unique').on(t.storeId, t.referredCustomerId),
    index('referrals_referrer_idx').on(t.referrerCustomerId),
    index('referrals_code_idx').on(t.storeId, t.code),
  ],
)

/** تجارب A/B — على السعر أو الصورة أو الوصف */
export const experiments = pgTable(
  'experiments',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    storeId: uuid('store_id').notNull().references(() => stores.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    target: text('target').$type<'product' | 'funnel'>().notNull().default('product'),
    targetId: uuid('target_id').notNull(),
    field: text('field').$type<'price' | 'image' | 'title' | 'description' | 'cta'>().notNull(),
    variantA: jsonb('variant_a').$type<Record<string, unknown>>().notNull().default({}),
    variantB: jsonb('variant_b').$type<Record<string, unknown>>().notNull().default({}),
    splitBps: integer('split_bps').notNull().default(5000), // 50/50
    viewsA: integer('views_a').notNull().default(0),
    viewsB: integer('views_b').notNull().default(0),
    ordersA: integer('orders_a').notNull().default(0),
    ordersB: integer('orders_b').notNull().default(0),
    revenueA: money('revenue_a'),
    revenueB: money('revenue_b'),
    status: text('status').$type<'draft' | 'running' | 'paused' | 'finished'>().notNull().default('draft'),
    winner: text('winner').$type<'a' | 'b' | null>(),
    startedAt: timestamp('started_at', { withTimezone: true }),
    endedAt: timestamp('ended_at', { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [index('experiments_store_idx').on(t.storeId, t.status)],
)

export type CampaignStatus = 'draft' | 'sending' | 'sent' | 'failed'
/** مين بيستقبل الحملة */
export type CampaignAudience = 'all' | 'buyers' | 'non_buyers' | 'abandoned'

/**
 * حملة بريدية.
 *
 * ## ليه الإرسال على دفعات مش مرة واحدة
 * متجر بعشرة آلاف مشترك معناه عشرة آلاف نداء لمزوّد البريد. النداء
 * ده لو اتعمل في طلب واحد بيتقطع عند مهلة الدالة، وبيسيب نص العملاء
 * اتبعتلهم والنص التاني لأ — ومحدّش يعرف فين وقف. الحملة بتتقسّم
 * على مهام في الطابور، وكل مهمة بتاخد دفعة وبتحجز اللي بعدها.
 *
 * ## والعدّاد بيتقدّم مع الدفعة
 * `sentCount` بيتحدّث بعد كل دفعة. لو الطابور وقف، التاجر بيشوف
 * «اتبعت ٤٠٠ من ١٢٠٠» — بدل شريط تقدّم واقف مالوش معنى.
 */
export const campaigns = pgTable(
  'campaigns',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    storeId: uuid('store_id').notNull().references(() => stores.id, { onDelete: 'cascade' }),

    name: text('name').notNull(),
    subject: text('subject').notNull(),
    /** نص الرسالة كما كتبه التاجر — بيتحوّل لقالب المتجر وقت الإرسال */
    body: text('body').notNull(),
    /** زر الدعوة — اختياري، وبيتحطّ في نص الرسالة */
    ctaLabel: text('cta_label'),
    ctaUrl: text('cta_url'),

    audience: text('audience').$type<CampaignAudience>().notNull().default('all'),
    status: text('status').$type<CampaignStatus>().notNull().default('draft'),

    /**
     * حجم الجمهور وقت الإرسال — **لقطة لا حساب لحظي**.
     *
     * لو حسبناه كل مرة، التقرير بيتغيّر بعد الحملة كل ما عميل جديد
     * يشترك — والتاجر بيشوف «اتبعت ٤٠٠ من ٥٠٠» على حملة خلصت.
     */
    audienceCount: integer('audience_count').notNull().default(0),
    sentCount: integer('sent_count').notNull().default(0),
    failedCount: integer('failed_count').notNull().default(0),

    startedAt: timestamp('started_at', { withTimezone: true }),
    finishedAt: timestamp('finished_at', { withTimezone: true }),
    createdBy: uuid('created_by'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('campaigns_store_idx').on(t.storeId, t.createdAt)],
)
